export type Bindings = {
  ASSETS?: {
    fetch: typeof fetch
  }
  DB: D1Database
  BETTER_AUTH_SECRET?: string
  BETTER_AUTH_URL?: string
  TOKENBOARD_COLLECTOR_REPO_URL?: string
  TOKENBOARD_COLLECTOR_REF?: string
  TOKENBOARD_DAILY_REPORT_HISTORY_DAYS?: string
  TOKENBOARD_USAGE_SUMMARY_STRICT?: string
  TOKENBOARD_USAGE_SUMMARY_BACKFILL_LIMIT?: string
  TOKENBOARD_WEBHOOK_LOG_RETENTION_DAYS?: string
  TOKENBOARD_WEBHOOK_CRON_BATCH_SIZE?: string
  TOKENBOARD_MODEL_PRICING_SYNC_ENABLED?: string
  TOKENBOARD_MODEL_PRICING_SYNC_INTERVAL_HOURS?: string
  TOKENBOARD_MODEL_PRICING_SOURCE_URL?: string
  TOKENBOARD_MODEL_PRICING_SYNC_TOKEN?: string
  TOKENBOARD_STEP_UP_REQUIRED?: string
  WEBHOOK_ENCRYPTION_KEY?: string
  GITHUB_CLIENT_ID?: string
  GITHUB_CLIENT_SECRET?: string
}

export type AppEnv = {
  Bindings: Bindings
}
