import { spawn } from 'node:child_process'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { assertClaudeSettingsValid, getClaudeHookStatus, installClaudeHook, uninstallClaudeHook } from './claude-hook.mjs'
import { configDir, parseArgs } from './config.mjs'
import { assertCodexNotifyWritable, getCodexHookStatus, installCodexHook, uninstallCodexHook } from './codex-hook.mjs'
import { claudeSource, codexSource, isTokenBoardNotifyHandler, nodeFs, notifyHandlerMarker, readOptional, readSources, removeNotifyHandler } from './hooks-utils.mjs'

export function hookPaths({ homeDir = homedir(), stateDir = configDir(), env = process.env } = {}) {
  const tokenboardHome = stateDir
  const binDir = join(tokenboardHome, 'bin')
  const codexHome = resolveEnvPath(env.CODEX_HOME) || join(homeDir, '.codex')
  const claudeHome = resolveEnvPath(env.CLAUDE_CONFIG_DIR) || resolveEnvPath(env.CLAUDE_HOME) || join(homeDir, '.claude')
  return {
    stateDir: tokenboardHome,
    binDir,
    notifyPath: join(binDir, 'notify.cjs'),
    notifyScriptPath: fileURLToPath(new URL('./notify.mjs', import.meta.url)),
    codexConfigPath: join(codexHome, 'config.toml'),
    codexOriginalPath: join(tokenboardHome, 'codex_notify_original.json'),
    claudeSettingsPath: join(claudeHome, 'settings.json')
  }
}

export function installHooks(options = {}) {
  const flags = options.flags || parseArgs(options.argv || process.argv.slice(2))
  const paths = options.paths || hookPaths(options)
  const fs = options.fs || nodeFs()
  const nodePath = options.nodePath || process.execPath
  const platform = options.platform || process.platform
  const sources = readSources(flags.source || flags.sources || 'all')
  validateHookTargets({ sources, paths, fs })

  fs.mkdir(paths.binDir, { recursive: true, mode: 0o700 })
  fs.writeFile(paths.notifyPath, buildNotifyHandler({
    stateDir: paths.stateDir,
    notifyScriptPath: paths.notifyScriptPath,
    nodePath
  }), { mode: 0o700 })

  const results = []
  if (sources.includes(codexSource)) {
    results.push(installCodexHook({ paths, fs, nodePath, platform }))
  }
  if (sources.includes(claudeSource)) {
    results.push(installClaudeHook({ paths, fs, nodePath, platform }))
  }
  const installedHooks = {
    codex: getCodexHookStatus({ paths, fs }),
    claudeCode: getClaudeHookStatus({ paths, fs, nodePath, platform })
  }
  if (canRemoveNotifyHandler(installedHooks)) {
    removeNotifyHandler({ paths, fs })
  }
  return { notifyPath: paths.notifyPath, hooks: results }
}

export function uninstallHooks(options = {}) {
  const flags = options.flags || parseArgs(options.argv || process.argv.slice(2))
  const paths = options.paths || hookPaths(options)
  const fs = options.fs || nodeFs()
  const nodePath = options.nodePath || process.execPath
  const platform = options.platform || process.platform
  const sources = readSources(flags.source || flags.sources || 'all')
  validateHookTargets({ sources, paths, fs })
  const results = []

  if (sources.includes(codexSource)) {
    results.push(uninstallCodexHook({ paths, fs }))
  }
  if (sources.includes(claudeSource)) {
    results.push(uninstallClaudeHook({ paths, fs, nodePath, platform }))
  }

  const remainingHooks = {
    codex: getCodexHookStatus({ paths, fs }),
    claudeCode: getClaudeHookStatus({ paths, fs, nodePath, platform })
  }
  const notifyRemoved = canRemoveNotifyHandler(remainingHooks)
    ? removeNotifyHandler({ paths, fs })
    : false
  return { notifyPath: paths.notifyPath, notifyRemoved, hooks: results }
}

export function hookStatus(options = {}) {
  const paths = options.paths || hookPaths(options)
  const fs = options.fs || nodeFs()
  const nodePath = options.nodePath || process.execPath
  const platform = options.platform || process.platform
  return {
    notifyPath: paths.notifyPath,
    notifyHandler: isTokenBoardNotifyHandler(readOptional(paths.notifyPath, fs)) ? 'installed' : 'not-installed',
    codex: getCodexHookStatus({ paths, fs }),
    claudeCode: getClaudeHookStatus({ paths, fs, nodePath, platform })
  }
}

export function buildNotifyHandler({ stateDir, notifyScriptPath, nodePath }) {
  return [
    notifyHandlerHeader({ stateDir, notifyScriptPath }),
    notifyHandlerArgParser(),
    notifyHandlerMainFlow(),
    notifyHandlerOriginalForwarder(),
    notifyHandlerHelpers()
  ].join('\n')
}

function notifyHandlerHeader({ stateDir, notifyScriptPath }) {
  return `#!/usr/bin/env node
// ${notifyHandlerMarker} - Auto-generated by TokenBoard. Do not edit.
"use strict";

const { appendFileSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");
const { spawn } = require("node:child_process");
const { homedir } = require("node:os");

const STATE_DIR = ${JSON.stringify(stateDir)};
const SIGNAL_DIR = join(STATE_DIR, "notify.signal.d");
const NODE_PATH = process.execPath;
const NOTIFY_SCRIPT = ${JSON.stringify(notifyScriptPath)};
const SELF_PATH = resolve(__filename);
const HOME_DIR = homedir();
`
}

function notifyHandlerArgParser() {
  return `
const rawArgs = process.argv.slice(2);
let source = "";
const payloadArgs = [];
for (let index = 0; index < rawArgs.length; index += 1) {
  const arg = rawArgs[index];
  if (!source && arg === "--source") {
    source = rawArgs[index + 1] || source;
    index += 1;
    continue;
  }
  if (!source && arg.startsWith("--source=")) {
    source = arg.slice("--source=".length) || source;
    continue;
  }
  payloadArgs.push(arg);
}

if (source !== "codex" && source !== "claude-code") {
  recordHandlerError("source", new Error("Unsupported TokenBoard hook source"));
  process.exit(0);
}
`
}

function notifyHandlerMainFlow() {
  return `
try {
  mkdirSync(STATE_DIR, { recursive: true, mode: 0o700 });
  const signalPayload = JSON.stringify({
    source,
    requestedAt: new Date().toISOString(),
  }) + "\\n";
  let queueError;
  try {
    writeQueuedSignal(signalPayload);
  } catch (error) {
    queueError = error;
  }
  appendFileSync(join(STATE_DIR, "notify.signal"), signalPayload, "utf8");
  if (queueError) throw queueError;
} catch (error) {
  recordHandlerError("enqueue", error);
}

try {
  const child = spawn(NODE_PATH, [NOTIFY_SCRIPT, "--source", source], {
    detached: true,
    stdio: "ignore",
    env: {
      ...process.env,
      TOKENBOARD_CONFIG_DIR: STATE_DIR,
      TOKENBOARD_STATE_DIR: STATE_DIR,
    },
  });
  child.unref();
} catch (error) {
  recordHandlerError("background", error);
}
`
}

function notifyHandlerOriginalForwarder() {
  return `
if (source === "codex") {
  try {
    const original = JSON.parse(readFileSync(join(STATE_DIR, "codex_notify_original.json"), "utf8"));
    const cmd = Array.isArray(original && original.notify) ? original.notify : null;
    if (cmd && cmd.length > 0 && !isSelfNotify(cmd)) {
      const child = spawn(cmd[0], [...cmd.slice(1), ...payloadArgs], {
        detached: true,
        stdio: "ignore",
        env: { ...process.env },
      });
      child.unref();
    }
  } catch (error) {
    if (!isMissingFileError(error)) recordHandlerError("original", error);
  }
}

process.exit(0);
`
}

function notifyHandlerHelpers() {
  return `
function isSelfNotify(cmd) {
  return cmd.some((part) => {
    if (typeof part !== "string") return false;
    if (!part.includes("notify.cjs")) return false;
    if (part.includes(SELF_PATH)) return true;
    const homePath = SELF_PATH.startsWith(HOME_DIR) ? "~" + SELF_PATH.slice(HOME_DIR.length) : "";
    if (homePath && part.includes(homePath)) return true;
    const resolved = part.startsWith("~/") ? join(HOME_DIR, part.slice(2)) : resolve(part);
    return resolved === SELF_PATH;
  });
}

function recordHandlerError(stage, error) {
  try {
    mkdirSync(STATE_DIR, { recursive: true, mode: 0o700 });
    const message = error && error.message ? error.message : String(error);
    appendFileSync(join(STATE_DIR, "notify-handler-errors.log"), JSON.stringify({
      stage,
      message,
      at: new Date().toISOString(),
    }) + "\\n", "utf8");
  } catch (_) {}
}

function isMissingFileError(error) {
  return error && error.code === "ENOENT";
}

function writeQueuedSignal(payload) {
  mkdirSync(SIGNAL_DIR, { recursive: true, mode: 0o700 });
  const name = Date.now() + "-" + process.pid + "-" + Math.random().toString(36).slice(2);
  const tempPath = join(SIGNAL_DIR, "." + name + ".tmp");
  const finalPath = join(SIGNAL_DIR, name + ".json");
  writeFileSync(tempPath, payload, { encoding: "utf8", flag: "wx", mode: 0o600 });
  try {
    renameSync(tempPath, finalPath);
  } catch (error) {
    try {
      unlinkSync(tempPath);
    } catch (_) {}
    throw error;
  }
}
`
}

function validateHookTargets({ sources, paths, fs }) {
  if (sources.includes(codexSource)) {
    assertCodexNotifyWritable({ paths, fs })
  }
  if (sources.includes(claudeSource)) {
    assertClaudeSettingsValid({ paths, fs })
  }
}

function canRemoveNotifyHandler(status) {
  return status.codex === 'not-installed' && status.claudeCode === 'not-installed'
}

function resolveEnvPath(value) {
  return typeof value === 'string' && value.trim() ? resolve(value) : null
}

function runCli(command) {
  try {
    const result = command()
    console.log(JSON.stringify(result, null, 2))
  } catch (error) {
    console.error(error.message)
    process.exit(1)
  }
}

export function runInstallHooksCli() {
  runCli(() => installHooks())
}

export function runUninstallHooksCli() {
  runCli(() => uninstallHooks())
}
